import turtle
john = turtle.Turtle()
mike = turtle.Turtle()
fred = turtle.Turtle()
henry = turtle.Turtle()
bob = turtle.Turtle()
jake = turtle.Turtle()
john.speed(30)
mike.speed(30)
fred.speed(30)
henry.speed(30)
bob.speed(30)
jake.speed(30)
turtle.bgcolor("Light Sky Blue")

bob.penup()
bob.goto(-125,-200)
bob.color("Pale Goldenrod")
bob.begin_fill()
bob.left(90)
bob.pendown()
bob.forward(195)
bob.right(45)
bob.forward(165)
bob.right(90)
bob.forward(165)
bob.right(45)
bob.forward(195)
bob.end_fill()

mike.penup()
mike.goto(-150,-40)
mike.color("Firebrick")
mike.pensize(25)
mike.pendown()
mike.right(-45)
mike.forward(200)
mike.right(90)
mike.forward(200)

fred.penup()
fred.goto(-30,-200)
fred.color("Saddle Brown")
fred.begin_fill()
fred.left(90)
fred.pendown()
fred.forward(100)
fred.right(90)
fred.forward(50)
fred.right(90)
fred.forward(100)
fred.end_fill()
fred.goto(0,-150)
fred.color("Gold")
fred.begin_fill()
fred.circle(5)
fred.end_fill()

henry.penup()
henry.pensize(100)
henry.goto(-270,-200)
henry.left(90)
henry.color("Sienna")
henry.pendown()
henry.forward(200)
henry.pensize(10)
henry.begin_fill()
henry.color("Lime Green")
henry.circle(50)
henry.end_fill()
henry.right(180)
henry.begin_fill()
henry.circle(50)
henry.end_fill()
henry.left(90)
henry.begin_fill()
henry.circle(50)
henry.end_fill()

henry.penup()
henry.pensize(100)
henry.goto(270,-200)
henry.left(90)
henry.color("Sienna")
henry.pendown()
henry.forward(200)
henry.pensize(10)
henry.begin_fill()
henry.color("Lime Green")
henry.circle(50)
henry.end_fill()
henry.right(180)
henry.begin_fill()
henry.circle(50)
henry.end_fill()
henry.left(90)
henry.begin_fill()
henry.circle(50)
henry.end_fill()

john.penup()
john.goto(-360,-200)
john.begin_fill()
john.color("dark green")
john.pendown()
john.forward(800)
john.right(90)
john.forward(200)
john.right(90)
john.forward(800)
john.end_fill()

jake.penup()
jake.goto(200,200)
jake.begin_fill()
jake.color("white")
jake.pendown()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(10)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(20)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(30)
jake.begin_fill()
jake.circle(30)
jake.end_fill()

jake.penup()
jake.goto(-200,150)
jake.begin_fill()
jake.color("white")
jake.pendown()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(10)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(20)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(30)
jake.begin_fill()
jake.circle(30)
jake.end_fill()

jake.penup()
jake.goto(0,230)
jake.begin_fill()
jake.color("white")
jake.pendown()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(10)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(20)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(30)
jake.begin_fill()
jake.circle(30)
jake.end_fill()

jake.penup()
jake.goto(-300,250)
jake.begin_fill()
jake.color("white")
jake.pendown()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(10)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(20)
jake.end_fill()
jake.right(50)
jake.begin_fill()
jake.circle(30)
jake.end_fill()
jake.right(30)
jake.begin_fill()
jake.circle(30)
jake.end_fill()

john.penup()
john.color("Light Sky Blue")
john.goto(200,130)
mike.penup()
mike.color("Light Sky Blue")
mike.goto(200,130)
fred.penup()
fred.color("Light Sky Blue")
fred.goto(200,130)
henry.penup()
henry.color("Light Sky Blue")
henry.goto(200,130)
bob.penup()
bob.color("Light Sky Blue")
bob.goto(200,130)

turtle.exitonclick()
