import turtle
john = turtle.Turtle()
mike = turtle.Turtle()
fred = turtle.Turtle()
henry = turtle.Turtle()
bob = turtle.Turtle()
john.speed(30)
mike.speed(30)
fred.speed(30)
henry.speed(30)
bob.speed(30)
turtle.bgcolor("Light Sky Blue")

mike.penup()
mike.goto(-150,0)
mike.color("Firebrick")
mike.pensize(25)
mike.pendown()
mike.right(-45)
mike.forward(200)
mike.right(90)
mike.forward(200)

bob.penup()
bob.goto(-125,-10)
bob.pendown()
bob.color("Pale Goldenrod")
bob.begin_fill()
bob.left(40)
bob.forward(178)
bob.left(180)
bob.forward(230)
bob.left(90)
bob.forward(179)
bob.left(45)
bob.forward(160)
bob.left(90)
bob.forward(160)
bob.end_fill()

fred.penup()
fred.goto(-30,-200)
fred.color("Saddle Brown")
fred.begin_fill()
fred.left(90)
fred.pendown()
fred.forward(100)
fred.right(90)
fred.forward(50)
fred.right(90)
fred.forward(100)
fred.end_fill()
fred.goto(0,-150)
fred.color("Gold")
fred.begin_fill()
fred.circle(5)
fred.end_fill()

henry.penup()
henry.pensize(100)
henry.goto(-270,-200)
henry.left(90)
henry.color("Sienna")
henry.pendown()
henry.forward(200)
henry.pensize(10)
henry.begin_fill()
henry.color("Lime Green")
henry.circle(50)
henry.end_fill()
henry.right(180)
henry.begin_fill()
henry.circle(50)
henry.end_fill()
henry.left(90)
henry.begin_fill()
henry.circle(50)
henry.end_fill()

henry.penup()
henry.pensize(100)
henry.goto(270,-200)
henry.left(90)
henry.color("Sienna")
henry.pendown()
henry.forward(200)
henry.pensize(10)
henry.begin_fill()
henry.color("Lime Green")
henry.circle(50)
henry.end_fill()
henry.right(180)
henry.begin_fill()
henry.circle(50)
henry.end_fill()
henry.left(90)
henry.begin_fill()
henry.circle(50)
henry.end_fill()

john.penup()
john.goto(-360,-200)
john.begin_fill()
john.color("dark green")
john.pendown()
john.forward(800)
john.right(90)
john.forward(200)
john.right(90)
john.forward(800)
john.end_fill()

turtle.exitonclick()