import turtle
john = turtle.Turtle()
mike = turtle.Turtle()
fred = turtle.Turtle()
henry = turtle.Turtle()
john.speed(30)
mike.speed(30)
fred.speed(30)
henry.speed(30)

john.penup()
john.goto(-360,-200)
john.begin_fill()
john.color("dark green")
john.pendown()
john.forward(800)
john.right(90)
john.forward(200)
john.right(90)
john.forward(800)
john.end_fill()

mike.penup()
mike.goto(-150,0)
mike.color("red")
mike.pensize(15)
mike.pendown()
mike.right(-45)
mike.forward(200)
mike.right(90)
mike.forward(200)
mike.penup()
mike.goto(-134,-10)
mike.pendown()
mike.color("Pale Goldenrod")
mike.right(42)
mike.forward(100)


turtle.exitonclick()